# Generated by Django 2.2 on 2020-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='mobile_number',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Alternate Phone number'),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
