# Generated by Django 2.2 on 2020-08-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_auto_20200809_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
